version: "3.7"

services:
  caddy:
    image: aryaniyaps/securechat-caddy:latest
    volumes:
      - caddy_data:/data/caddy
    environment:
      DIGITALOCEAN_API_TOKEN: ${DIGITALOCEAN_API_TOKEN}
      ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - seaweedfs-s3
      - ws-server

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    image: aryaniyaps/securechat:latest
    environment:
      # Prisma
      DATABASE_URL: ${DATABASE_URL}
      # Next Auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      # Next Auth Google Provider
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Next Auth Email Provider
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_FROM: ${EMAIL_FROM}
      # S3 Configuration
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

      # WS Server Configuration
      WS_SERVER_URL: ${WS_SERVER_URL}

    depends_on:
      - mongodb
      - seaweedfs-s3
      - ws-server

  ws-server:
    image: aryaniyaps/securechat-ws-server:latest
    environment:
      CONNECT_PROXY_URL: ${CONNECT_PROXY_URL}

  seaweedfs-master:
    image: chrislusf/seaweedfs:3.55
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    command: "master -mdir /data -ip=seaweedfs-master -ip.bind=0.0.0.0 -metricsPort=9324"
    volumes:
      - seaweedfs_master_data:/data

  seaweedfs-volume:
    image: chrislusf/seaweedfs:3.55
    ports:
      - "8080:8080"
      - "18080:18080"
      - "9325:9325"
    depends_on:
      - seaweedfs-master
    command: "volume -max=2 -mserver=seaweedfs-master:9333 -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325"

  seaweedfs-filer:
    image: chrislusf/seaweedfs:3.55
    ports:
      - "8888:8888"
      - "18888:18888"
      - "9326:9326"
    depends_on:
      - seaweedfs-master
    command: "filer -master=seaweedfs-master:9333 -ip.bind=0.0.0.0 -metricsPort=9326"
    tty: true
    stdin_open: true

  seaweedfs-s3:
    build:
      context: ../weed-s3
      dockerfile: Dockerfile
      target: dev-container
    ports:
      - "8333:8333"
      - "9327:9327"
    depends_on:
      - seaweedfs-master
      - seaweedfs-filer
    command: "s3 -filer=seaweedfs-filer:8888 -ip.bind=0.0.0.0 -metricsPort=9327 -config=/config.json"

volumes:
  seaweedfs_master_data:
    driver: local
  caddy_data:
    driver: local
  mongodb_data:
    driver: local
