version: "3.7"

services:
  caddy:
    image: aryaniyaps/securechat-caddy:latest
    volumes:
      - caddy_data:/data/caddy
    environment:
      DIGITALOCEAN_API_TOKEN: ${DIGITALOCEAN_API_TOKEN}
      ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - seaweedfs-s3
      - ws-server

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    image: aryaniyaps/securechat:latest
    environment:
      # Prisma
      DATABASE_URL: ${DATABASE_URL}
      # Next Auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      # Next Auth Google Provider
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Next Auth Email Provider
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_FROM: ${EMAIL_FROM}
      # S3 Configuration
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      S3_REGION: ${S3_REGION}
      S3_AVATAR_BUCKET_NAME: ${S3_AVATAR_BUCKET_NAME}
      S3_MEDIA_BUCKET_NAME: ${S3_MEDIA_BUCKET_NAME}

      # WS Server Configuration
      WS_SERVER_URL: ${WS_SERVER_URL}

    depends_on:
      - mongodb
      - seaweedfs-s3
      - ws-server

  ws-server:
    image: aryaniyaps/securechat-ws-server:latest
    environment:
      CONNECT_PROXY_URL: ${CONNECT_PROXY_URL}

  seaweedfs-master:
    image: chrislusf/seaweedfs:3.56
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    command: "master -mdir=/data/master -volumePreallocate=false -ip=seaweedfs-master -ip.bind=0.0.0.0 -metricsPort=9324"
    volumes:
      - seaweedfs_data:/data/master

  seaweedfs-volume:
    image: chrislusf/seaweedfs:3.56
    ports:
      - "8080:8080"
      - "18080:18080"
      - "9325:9325"
    depends_on:
      - seaweedfs-master
    command: "volume -max=50 -mserver=seaweedfs-master:9333 -ip.bind=0.0.0.0 -port=8080 -dir=/data/volume -metricsPort=9325"
    volumes:
      - seaweedfs_data:/data/volume

  seaweedfs-s3:
    image: aryaniyaps/securechat-weed-s3:latest
    ports:
      - "8333:8333"
      - "9327:9327"
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    # we are overriding the entrypoint, so we need to prefix our command with `weed`.
    # this won't be necessary if we are using the default entrypoint.
    command: "weed -v 9 filer -master=seaweedfs-master:9333 -s3 -metricsPort=9327 -ip.bind=0.0.0.0 -s3.config=/config.json"
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

volumes:
  seaweedfs_data:
    driver: local
  caddy_data:
    driver: local
  mongodb_data:
    driver: local
