version: "3.7"

services:
  caddy:
    image: aryaniyaps/securechat-caddy:latest
    volumes:
      - caddy_data:/data/caddy
    environment:
      DIGITALOCEAN_API_TOKEN: ${DIGITALOCEAN_API_TOKEN}
      ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - minio
      - ws-server

  minio:
    image: bitnami/minio:2023
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    image: aryaniyaps/securechat:latest
    environment:
      # Prisma
      DATABASE_URL: ${DATABASE_URL}
      # Next Auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      # Next Auth Google Provider
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Next Auth Email Provider
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_FROM: ${EMAIL_FROM}
      # MinIO Configuration
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_END_POINT: ${MINIO_END_POINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

      # Centrifugo Configuration
      CENTRIFUGO_URL: ${CENTRIFUGO_URL}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}

    depends_on:
      - mongodb
      - minio
      - ws-server

  ws-server:
    image: aryaniyaps/securechat-ws-server:latest

volumes:
  minio_data:
    driver: local
  caddy_data:
    driver: local
  mongodb_data:
    driver: local
