version: '3.7'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000

    command: server /data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: sh -c "npm run prisma:migrate && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - minio
    env_file:
    - .env

volumes:
  minio_data:
  db_data:
