version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  minio_data:
  db_data:
