version: "3.7"

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    command: server /data

  db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    depends_on:
      - db
      - minio
      - soketi
    env_file:
      - .env

  soketi:
    restart: unless-stopped
    image: "quay.io/soketi/soketi:0.17-16-alpine"
    ports:
      - 6001:6001
    networks:
      - soketi_network

volumes:
  minio_data:
  db_data:

networks:
  soketi_network:
    driver: bridge
