version: "3.7"

services:
  caddy:
    build:
      context: ../caddy
      dockerfile: Dockerfile
      target: dev-container
    volumes:
      - caddy_data:/data/caddy
    ports:
      - "80:80"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - app
      - minio
      - centrifugo

  minio:
    image: bitnami/minio:2023
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    ports:
      - "9000:9000"
      - "9001:9001"

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_ROOT_USER: ${MONGO_USER}
      MONGODB_REPLICA_SET_KEY: ${MONGO_REPLICA_SET_KEY}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
      target: dev-container
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        # MINIO Public Information
        NEXT_PUBLIC_MINIO_ENDPOINT: ${NEXT_PUBLIC_MINIO_ENDPOINT}
        NEXT_PUBLIC_MINIO_BUCKET: ${NEXT_PUBLIC_MINIO_BUCKET}
        # Centrifugo Public Information
        NEXT_PUBLIC_CENTRIFUGO_URL: ${NEXT_PUBLIC_CENTRIFUGO_URL}
    working_dir: /workspace/app
    volumes:
      - ../:/workspace:cached
      - /workspace/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
      - minio
      - centrifugo
    environment:
      # Prisma
      DATABASE_URL: ${DATABASE_URL}
      # Next Auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      # Next Auth Google Provider
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Next Auth Email Provider
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_FROM: ${EMAIL_FROM}
      # MinIO Configuration
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_END_POINT: ${MINIO_END_POINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

      # Centrifugo Configuration
      CENTRIFUGO_URL: ${CENTRIFUGO_URL}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
    ports:
      - "3000:3000"

  centrifugo:
    build:
      context: ../centrifugo
      dockerfile: Dockerfile
      target: dev-container
    environment:
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

  mailserver:
    build:
      context: ../mailserver
      dockerfile: Dockerfile
      args:
        EMAIL_USERNAME: ${EMAIL_USERNAME}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    environment:
      ENABLE_RSPAMD: 1
      ENABLE_AMAVIS: 0
      ENABLE_OPENDKIM: 0
      ENABLE_OPENDMARC: 0
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
    hostname: mail.vnadi.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - mailserver_data:/var/mail
      - mailserver_state:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

volumes:
  minio_data:
    driver: local
  caddy_data:
    driver: local
  mongodb_data:
    driver: local
  mailserver_data:
    driver: local
  mailserver_state:
    driver: local
