version: "3.7"

services:
  caddy:
    image: caddy:2.7-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data/caddy
    ports:
      - 80:80
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - app
      - minio
      - centrifugo

  minio:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001

  mongodb:
    image: bitnami/mongodb:6.0
    restart: unless-stopped
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_ROOT_USER=${MONGO_USER}
      - MONGODB_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: development
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        # MINIO Public Information
        NEXT_PUBLIC_MINIO_ENDPOINT: ${NEXT_PUBLIC_MINIO_ENDPOINT}
        NEXT_PUBLIC_MINIO_BUCKET: ${NEXT_PUBLIC_MINIO_BUCKET}

        # Centrifugo Public Information
        NEXT_PUBLIC_CENTRIFUGO_URL: ${NEXT_PUBLIC_CENTRIFUGO_URL}
    volumes:
      - ..:/workspace
    depends_on:
      - mongodb
      - minio
      - centrifugo
    environment:
      # Prisma
      DATABASE_URL: ${DATABASE_URL}
      # Next Auth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      # Next Auth Google Provider
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Next Auth Email Provider
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_FROM: ${EMAIL_FROM}
      # MinIO Configuration
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_END_POINT: ${MINIO_END_POINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

      # Centrifugo Configuration
      CENTRIFUGO_URL: ${CENTRIFUGO_URL}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
    ports:
      - 3000:3000

  centrifugo:
    image: centrifugo/centrifugo:v5
    environment:
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  minio_data:
    driver: local
  caddy_data:
    driver: local
  mongodb_data:
    driver: local
