name: Build and Push NextJS App Docker Image

on:
  push:
    branches:
      - main
    paths:
      - app/**

  pull_request:
    paths:
      - app/**

jobs:
  build_securechat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push SecureChat NextJS Docker image
        uses: docker/build-push-action@v2
        env:
          NEXT_PUBLIC_SITE_URL: https://vnadi.com
          NEXT_PUBLIC_S3_ENDPOINT: https://s3.vnadi.com
          NEXT_PUBLIC_S3_BUCKET: avatars
        with:
          context: ./app
          push: true
          target: production
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/securechat:latest
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ env.NEXT_PUBLIC_SITE_URL }}

            NEXT_PUBLIC_S3_ENDPOINT=${{ env.NEXT_PUBLIC_S3_ENDPOINT }}
            NEXT_PUBLIC_S3_BUCKET=${{ env.NEXT_PUBLIC_S3_BUCKET }}
