name: Build and Push NextJS App Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_securechat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push SecureChat NextJS Docker image
        uses: docker/build-push-action@v2
        env:
          NEXT_PUBLIC_SITE_URL: https://vnadi.com
          NEXT_PUBLIC_MINIO_ENDPOINT: https://minio.vnadi.com
          NEXT_PUBLIC_MINIO_BUCKET: avatars
          NEXT_PUBLIC_CENTRIFUGO_URL: wss://vnadi.com/connection/websocket
        with:
          context: ./app
          push: true
          target: production
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/securechat:latest
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ env.NEXT_PUBLIC_SITE_URL }}

            NEXT_PUBLIC_MINIO_ENDPOINT=${{ env.NEXT_PUBLIC_MINIO_ENDPOINT }}
            NEXT_PUBLIC_MINIO_BUCKET=${{ env.NEXT_PUBLIC_MINIO_BUCKET }}

            NEXT_PUBLIC_CENTRIFUGO_URL=${{ env.NEXT_PUBLIC_CENTRIFUGO_URL }}
